### ISSUE TITLE
Add CONTRIBUTE.md

### ISSUE THREAD

**Issue by abdatta** [adarshsrivastava11/mess#1]
Please add a CONTRIBUTE.md file detailing how to set up the project on our local machine and start contributing to it.

**Comment by adarshsrivastava11** [comment]
I'll add you a collaborator, you send a PR adding the above mentioned file.

**Comment by abdatta** [comment]
Yeah but I need to know how to set up the repo. Only `git clone` won't do right? I'll have to set up Django and may be other things that you'll know better. That's why I made it an issue.
